"use client";
import { useMemo, useState } from "react";

const data={
 "車・カー用品":[["プリウス60系対応ドラレコ","¥19,800","在庫あり",4.8],["駐車監視対応ドラレコ","¥23,400","取付予約可",4.6],["前後2カメラモデル","¥15,900","残りわずか",4.4]],
 "書籍・コミック":[["AI仕事術 最新版","¥1,980","在庫あり",4.7],["地域DX実践ガイド","¥2,420","電子版あり",4.5],["小さな店のデータ活用","¥1,760","残りわずか",4.3]],
 "推し活・イベント":[["幕張イベント周辺ホテル","¥8,900〜","空室あり",4.8],["会場徒歩圏駐車場","¥1,200〜","予約可",4.6],["海外eSIM 3日間","¥780〜","即時発行",4.5]],
};
export default function Home(){const [genre,setGenre]=useState("車・カー用品");const[area,setArea]=useState("横浜市港北区");const[color,setColor]=useState("green");const[copied,setCopied]=useState(false);const items=useMemo(()=>data[genre as keyof typeof data],[genre]);return <main><header><a className="logo">RANK<span>KIT</span></a><nav><a href="#builder">ウィジェット作成</a><a href="#metrics">成果</a><button>＋ 新規作成</button></nav></header>
<section className="hero"><div><p className="eyebrow">REVENUE WIDGET STUDIO</p><h1>地域ランキングを、<br/><em>収益につながる部品</em>へ。</h1><p>価格だけで順位を決めず、在庫、情報鮮度、適合性、広告条件を明示した比較ウィジェットを各サイトへ共通配信します。</p><div className="hero-stats"><span><b>24</b>稼働中</span><span><b>4.8%</b>平均CTR</span><span><b>¥42</b>EPC</span></div></div><div className="orbit"><b>CTR</b><strong>4.8%</strong><span>前月比 +0.7pt</span><i/></div></section>
<section className="builder" id="builder"><div className="controls"><p className="eyebrow">BUILD</p><h2>ランキングを作成</h2><label>市区町村・駅<input value={area} onChange={e=>setArea(e.target.value)}/></label><label>ジャンル<select value={genre} onChange={e=>setGenre(e.target.value)}>{Object.keys(data).map(x=><option key={x}>{x}</option>)}</select></label><label>表示色<div className="colors">{["green","blue","orange"].map(x=><button aria-label={`${x}を選択`} key={x} className={`${x} ${color===x?"on":""}`} onClick={()=>setColor(x)}/>)}</div></label><div className="toggles"><label><input type="checkbox" defaultChecked/>価格を表示</label><label><input type="checkbox" defaultChecked/>在庫を表示</label><label><input type="checkbox" defaultChecked/>更新日時を表示</label><label><input type="checkbox" defaultChecked/>広告表記を表示</label></div><button className="copy" onClick={()=>{setCopied(true);navigator.clipboard?.writeText(`<div data-rankkit=\"${genre}\" data-area=\"${area}\"></div>`)}}>{copied?"✓ 埋め込みコードをコピー済み":"埋め込みコードをコピー"}</button></div>
<div className="preview"><div className="preview-head"><span>LIVE PREVIEW</span><div>スマホ　□</div></div><div className={`widget ${color}`}><div className="widget-title"><div><small>広告・PRを含みます</small><h2>{area}のおすすめ</h2><p>{genre}ランキング</p></div><span>最終更新<br/><b>10分前</b></span></div>{items.map((x,i)=><article key={x[0] as string}><b className="rank">{i+1}</b><div><h3>{x[0]}</h3><p>確認元：提携店舗・利用者報告</p><span>★ {x[3]}　<em>● {x[2]}</em></span></div><strong>{x[1]}<small>税込</small></strong><button>詳細を見る →</button></article>)}<footer>順位基準：在庫30%・評価25%・鮮度25%・価格20%　<a>算出方法</a></footer></div></div></section>
<section className="metrics" id="metrics"><div><p className="eyebrow">PERFORMANCE</p><h2>成果が見えるから、改善できる。</h2></div><div className="metric-grid"><article><span>表示回数</span><b>128,420</b><i><em style={{width:"78%"}}/></i><small>過去30日 +12.4%</small></article><article><span>クリック率</span><b>4.8%</b><i><em style={{width:"62%"}}/></i><small>目標 4.2%を達成</small></article><article><span>通知登録率</span><b>2.1%</b><i><em style={{width:"46%"}}/></i><small>入荷通知が最多</small></article><article><span>推定報酬</span><b>¥258,400</b><i><em style={{width:"70%"}}/></i><small>確定前の参考値</small></article></div></section>
<section className="principles"><article><b>01</b><h3>広告で順位を買わせない</h3><p>広告料とランキング算出を分離し、掲載条件を明示します。</p></article><article><b>02</b><h3>古い情報を下げる</h3><p>在庫・価格は時間経過で鮮度スコアを減衰させます。</p></article><article><b>03</b><h3>商品を正確に特定</h3><p>JAN、ISBN、型番、品番、車両適合を順位データに紐づけます。</p></article></section><footer className="site-footer"><div className="logo">RANK<span>KIT</span></div><p>地域型サイトのランキング・比較・収益計測基盤</p><p>© 2026 RankKit</p></footer></main>}
