"use client";
import { useMemo, useState } from "react";

const data: Record<string, [string, string, string, number][]> = {
  "車・カー用品":     [["プリウス60系対応ドラレコ","¥19,800","在庫あり",4.8],["駐車監視対応ドラレコ","¥23,400","取付予約可",4.6],["前後2カメラモデル","¥15,900","残りわずか",4.4],["スマートミラー型ドラレコ","¥28,500","在庫あり",4.7],["コンパクト高画質モデル","¥11,800","在庫あり",4.3]],
  "書籍・コミック":   [["AI仕事術 最新版","¥1,980","在庫あり",4.7],["地域DX実践ガイド","¥2,420","電子版あり",4.5],["小さな店のデータ活用","¥1,760","残りわずか",4.3],["ChatGPT完全攻略","¥1,650","在庫あり",4.6],["副業×AI稼ぎ方入門","¥1,540","電子版あり",4.4]],
  "推し活・イベント": [["幕張イベント周辺ホテル","¥8,900〜","空室あり",4.8],["会場徒歩圏駐車場","¥1,200〜","予約可",4.6],["海外eSIM 3日間","¥780〜","即時発行",4.5],["推し活バッグ大容量","¥3,980","在庫あり",4.7],["現地当日チェックイン対応宿","¥7,200〜","空室あり",4.5]],
  "グルメ・飲食店":   [["横浜中華街 人気点心セット","¥3,200","当日予約可",4.9],["地元農家の新鮮野菜BOX","¥2,980","毎週水曜発送",4.7],["老舗ラーメン 取り寄せセット","¥2,400","残りわずか",4.6],["クラフトビール6本セット","¥3,600","在庫あり",4.5],["地元焼肉 食べ放題ランチ","¥2,200","予約優先",4.8]],
  "美容・コスメ":     [["無添加スキンケアセット","¥4,980","在庫あり",4.8],["プレミアムシャンプー","¥2,800","残りわずか",4.6],["クレンジングバーム 大容量","¥3,200","在庫あり",4.7],["美白美容液 トライアル","¥1,980","初回限定",4.5],["天然成分ハンドクリーム","¥1,480","在庫あり",4.4]],
  "家電・ガジェット": [["ワイヤレスイヤホン ANC搭載","¥12,800","在庫あり",4.7],["スマートウォッチ 健康管理","¥18,500","残りわずか",4.6],["モバイルバッテリー 20000mAh","¥3,980","在庫あり",4.5],["ミニプロジェクター 4K対応","¥28,000","取寄せ可",4.8],["USB-Cハブ 7in1","¥4,200","在庫あり",4.4]],
  "旅行・宿泊":       [["箱根 露天風呂付き旅館","¥18,000〜","空室あり",4.9],["京都 町屋ゲストハウス","¥7,500〜","残り2室",4.7],["沖縄 オーシャンビューホテル","¥22,000〜","早割あり",4.8],["熱海 海一望温泉ホテル","¥15,800〜","空室あり",4.6],["軽井沢 ペンション 1泊朝食","¥9,800〜","空室あり",4.5]],
  "スポーツ・アウトドア":[["トレイルランニングシューズ","¥14,800","在庫あり",4.7],["UVカット ドライTシャツ","¥3,980","在庫あり",4.5],["折りたたみ自転車 7速","¥38,000","取付対応",4.6],["キャンプ用チタンクッカー","¥5,400","残りわずか",4.8],["防水トレッキングポール","¥6,200","在庫あり",4.4]],
  "ベビー・キッズ":   [["オーガニックコットン肌着 3枚組","¥2,980","在庫あり",4.8],["知育おもちゃ 積み木セット","¥4,500","在庫あり",4.7],["ベビーカー コンパクト折りたたみ","¥38,000","色選択可",4.6],["抗菌防臭ランドセル 黒","¥48,000","2027年度対応",4.9],["チャイルドシート 新生児対応","¥32,000","取付サービス付",4.7]],
  "ペット用品":       [["無添加ドッグフード 3kg","¥3,800","定期便あり",4.8],["猫砂 消臭炭入り 大容量","¥2,400","在庫あり",4.6],["ペット用GPS首輪","¥8,900","残りわずか",4.7],["自動給水器 ポンプ式","¥3,200","在庫あり",4.5],["小型犬用スリング バッグ","¥5,600","在庫あり",4.4]],
  "健康・医療":       [["乳酸菌サプリ 60日分","¥3,980","定期便割引",4.7],["血糖値サポート サプリ","¥4,200","初回半額",4.6],["プロテイン チョコ風味 1kg","¥4,800","在庫あり",4.8],["睡眠サポートドリンク","¥2,800","定期便あり",4.5],["フェムケアサプリ 30日分","¥3,600","在庫あり",4.4]],
  "食品・お取り寄せ": [["北海道産いくら醤油漬け 200g","¥4,980","冷凍便",4.9],["博多辛子明太子 1本物","¥3,800","チルド配送",4.8],["京都 老舗の柚子七味","¥1,480","在庫あり",4.6],["讃岐うどん 24食セット","¥2,980","常温便",4.7],["大分産純粋はちみつ 500g","¥2,400","在庫あり",4.5]],
  "インテリア・家具":  [["ソファーベッド 3way","¥48,000","送料無料",4.6],["スタンディングデスク 電動","¥58,000","組立て込み",4.8],["LED シーリングライト 調光","¥8,900","当日出荷",4.7],["ウォールシェルフ 3段","¥5,400","在庫あり",4.5],["防水ラグ 洗えるタイプ","¥4,200","カラー7色",4.4]],
  "DIY・工具":        [["電動ドライバーセット 18V","¥12,800","在庫あり",4.7],["3Mマスキングテープ 24本セット","¥1,980","在庫あり",4.6],["ペンキ 水性 4L 白","¥2,400","業務用",4.5],["折りたたみ作業台","¥8,900","耐荷重150kg",4.8],["電動サンダー 60W","¥6,200","在庫あり",4.4]],
  "ファッション":      [["撥水ストレッチパンツ","¥5,800","全5色",4.7],["UVカット カーディガン","¥3,980","在庫わずか",4.6],["本革スニーカー 軽量","¥14,800","サイズ22-28",4.8],["防シワ ドレスシャツ","¥4,200","在庫あり",4.5],["軽量ダウンジャケット","¥18,000","撥水加工",4.7]],
  "エンタメ・ゲーム":  [["Nintendo Switch ゲームカード","¥6,578","在庫あり",4.8],["PS5 追加コントローラー","¥8,980","残りわずか",4.6],["VR ヘッドセット スタンドアローン","¥52,800","取寄せ可",4.9],["格闘ゲーム 最新作","¥7,678","在庫あり",4.7],["リズムゲーム コントローラー","¥4,980","在庫あり",4.5]],
  "スキンケア・健康美":  [["ナイアシンアミド美容液 30ml","¥3,980","在庫あり",4.8],["ビタミンC誘導体セラム","¥4,200","残りわずか",4.7],["レチノール クリーム 50ml","¥5,800","在庫あり",4.6],["セラミド化粧水 200ml","¥2,980","定期便あり",4.5],["SPF50 日焼け止めミルク","¥2,200","在庫あり",4.4]],
  "不動産・引越し":   [["単身引越し ¥30,000〜対応","¥30,000〜","今月中の予約特典",4.7],["家具付き賃貸 横浜市","¥65,000〜/月","内見予約可",4.6],["マンション購入相談 無料","無料","今月10件限定",4.5],["不用品回収 軽トラ1台","¥8,000〜","即日対応可",4.8],["ハウスクリーニング 2LDK","¥25,000〜","平日割引",4.4]],
  "地元グルメ":       [["地域の人気パン屋 詰め合わせ","¥2,800","毎週限定数",4.9],["農家直送 旬の野菜セット","¥1,980","週1便",4.8],["地元醸造所クラフトジン","¥4,200","数量限定",4.7],["漁港直送 朝どれ干物","¥3,600","冷凍便",4.8],["老舗和菓子 季節の上生菓子","¥2,400","要予約",4.6]],
  "教育・オンライン学習":  [["プログラミング入門 30日コース","¥19,800","即時受講開始",4.7],["TOEIC対策 映像講座","¥14,800","添削付き",4.6],["動画編集マスターコース","¥24,800","生涯学習可",4.8],["FP3級 一発合格講座","¥9,800","模擬試験付き",4.5],["Python×AI データ分析","¥29,800","受講者2.3万人",4.7]],
};
export default function Home(){const [genre,setGenre]=useState("車・カー用品");const[area,setArea]=useState("横浜市港北区");const[color,setColor]=useState("green");const[copied,setCopied]=useState(false);const items=useMemo(()=>data[genre as keyof typeof data],[genre]);const genreKeys=Object.keys(data);return <main><header><a className="logo">RANK<span>KIT</span></a><nav><a href="#builder">ウィジェット作成</a><a href="#metrics">成果</a><button>＋ 新規作成</button></nav></header>
<section className="hero"><div><p className="eyebrow">REVENUE WIDGET STUDIO</p><h1>地域ランキングを、<br/><em>収益につながる部品</em>へ。</h1><p>価格だけで順位を決めず、在庫、情報鮮度、適合性、広告条件を明示した比較ウィジェットを各サイトへ共通配信します。</p><div className="hero-stats"><span><b>{genreKeys.length}</b>ジャンル対応</span><span><b>4.8%</b>平均CTR</span><span><b>¥42</b>EPC</span></div></div><div className="orbit"><b>CTR</b><strong>4.8%</strong><span>前月比 +0.7pt</span><i/></div></section>
<section className="builder" id="builder"><div className="controls"><p className="eyebrow">BUILD</p><h2>ランキングを作成</h2><label>市区町村・駅<input value={area} onChange={e=>setArea(e.target.value)}/></label><label>ジャンル（{genreKeys.length}種）<select value={genre} onChange={e=>setGenre(e.target.value)}>{genreKeys.map(x=><option key={x}>{x}</option>)}</select></label><label>表示色<div className="colors">{["green","blue","orange","violet","rose","dark"].map(x=><button aria-label={`${x}を選択`} key={x} className={`${x} ${color===x?"on":""}`} onClick={()=>setColor(x)}/>)}</div></label><div className="toggles"><label><input type="checkbox" defaultChecked/>価格を表示</label><label><input type="checkbox" defaultChecked/>在庫を表示</label><label><input type="checkbox" defaultChecked/>更新日時を表示</label><label><input type="checkbox" defaultChecked/>広告表記を表示</label></div><div style={{marginTop:"10px"}}><p style={{fontSize:".8rem",color:"#8b8099",marginBottom:"6px"}}>クイックプリセット</p><div style={{display:"flex",gap:"6px",flexWrap:"wrap"}}>{["グルメ・飲食店","美容・コスメ","旅行・宿泊","ベビー・キッズ"].map(p=><button key={p} style={{fontSize:".72rem",padding:"4px 10px",borderRadius:"20px",border:"1px solid #2e2648",background:"transparent",color:"#a78bfa",cursor:"pointer"}} onClick={()=>setGenre(p)}>{p}</button>)}</div></div><button className="copy" onClick={()=>{setCopied(true);navigator.clipboard?.writeText(`<div data-rankkit="${genre}" data-area="${area}" data-color="${color}"></div>\n<script src="https://rankkit.io/widget.js" async></script>`)}}>{copied?"✓ 埋め込みコードをコピー済み":"埋め込みコードをコピー"}</button>{copied&&<code style={{display:"block",marginTop:"8px",padding:"10px 12px",background:"#12101c",borderRadius:"6px",fontSize:".72rem",color:"#a78bfa",wordBreak:"break-all"}}>{`<div data-rankkit="${genre}" data-area="${area}" data-color="${color}"></div>`}<br/>{`<script src="https://rankkit.io/widget.js" async></script>`}</code>}</div>
<div className="preview"><div className="preview-head"><span>LIVE PREVIEW</span><div>スマホ　□</div></div><div className={`widget ${color}`}><div className="widget-title"><div><small>広告・PRを含みます</small><h2>{area}のおすすめ</h2><p>{genre}ランキング</p></div><span>最終更新<br/><b>10分前</b></span></div>{items.map((x,i)=><article key={x[0] as string}><b className="rank">{i+1}</b><div><h3>{x[0]}</h3><p>確認元：提携店舗・利用者報告</p><span>★ {x[3]}　<em>● {x[2]}</em></span></div><strong>{x[1]}<small>税込</small></strong><button>詳細を見る →</button></article>)}<footer>順位基準：在庫30%・評価25%・鮮度25%・価格20%　<a>算出方法</a></footer></div></div></section>
<section className="metrics" id="metrics"><div><p className="eyebrow">PERFORMANCE</p><h2>成果が見えるから、改善できる。</h2></div><div className="metric-grid"><article><span>表示回数</span><b>128,420</b><i><em style={{width:"78%"}}/></i><small>過去30日 +12.4%</small></article><article><span>クリック率</span><b>4.8%</b><i><em style={{width:"62%"}}/></i><small>目標 4.2%を達成</small></article><article><span>通知登録率</span><b>2.1%</b><i><em style={{width:"46%"}}/></i><small>入荷通知が最多</small></article><article><span>推定報酬</span><b>¥258,400</b><i><em style={{width:"70%"}}/></i><small>確定前の参考値</small></article></div></section>
<section className="principles"><article><b>01</b><h3>広告で順位を買わせない</h3><p>広告料とランキング算出を分離し、掲載条件を明示します。</p></article><article><b>02</b><h3>古い情報を下げる</h3><p>在庫・価格は時間経過で鮮度スコアを減衰させます。</p></article><article><b>03</b><h3>商品を正確に特定</h3><p>JAN、ISBN、型番、品番、車両適合を順位データに紐づけます。</p></article></section><footer className="site-footer"><div className="logo">RANK<span>KIT</span></div><p>地域型サイトのランキング・比較・収益計測基盤</p><p>© 2026 RankKit</p></footer></main>}
